name: 'Close PRs With Failing CI'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * MON,WED,FRI'

permissions:
  issues: write
  pull-requests: write
  checks: read
  statuses: read

jobs:
  close-failing-ci-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Process PRs with failing CI
        run: ./scripts/close-failing-ci-prs.sh -o "${{ github.repository_owner }}" -r "${{ github.event.repository.name }}" -t "${{ secrets.GITHUB_TOKEN }}" -l
